id: IC3443323
default_language: bo
source: https://www.lotsawahouse.org
initial_creation_type: web_scrap
imported: 2023-01-04 11:31:02.180459
last_modified: 2023-01-04 11:31:02.180478
source_metadata:
  collections:
  - Chatral Rinpoche
  - Works of Tibetan Masters
bases:
  '4617':
    title: 'Melodious Tambura of Delight: A Guide to Māratika Cave, Supreme Site of
      Immortality'
    base_file: 4617.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
